version: '3.8'

networks:
  nemonetwork:
    name: nemonetwork

services:

  nemo-web:
    container_name: nemo-web
    image: nemo-web
    build:
      context: .
      dockerfile: web/dockerfile
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - nemonetwork
    ports:
      - 6200:80
    restart: always
